name: Docker Image CI
#Deze workflow wordt uigevoerd bij elke push of pull naar de main branch
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest #draait op de nieuwste ubuntu in github actions

    steps:
      #haalt de code uit de repository
      - uses: actions/checkout@v4
      #setup node voor frontend
      - uses: actions/setup-node@v4
        with: node-version:'20'

      - name: Installeer frontend dependencies
        working-directory: client
        run: npm ci

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
