name: CI Pipeline

# Deze workflow draait bij elke push of pull request naar de main branch
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest # Draait op een Ubuntu VM

    steps:
      #haal de code uit de repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js voor frontend
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Installeer frontend dependencies
        working-directory: client
        run: npm install

      - name: Build frontend
        working-directory: client
        run: npm run build

      # --- Docker build voor backend ---
      - name: Build Docker image van de backend
        run: docker build -t my-backend:latest backend
